### PR TITLE
Projects page

### PR DESCRIPTION
**Pull request by Seneli**
This PR addresses #19 

Right now it just has dummy content in the project page that shows how the carousel shows different numbers of projects per section.

I'm not sure which color scheme to use for this component at the bottom though. Any input is appreciated ! 
Screen Shot 2023-02-08 at 11 14 25 AM

### CODE REVIEW

**Comment by hellomusa** [comment]
Nice job @Seneli !

I'm seeing these double scrollbars in the projects carousel:
image

Did you encounter that at all or could it just be something on my end? Maybe @AdiChops can check as well.

Also, the carousel previous/next arrows are hard to see. We should see if we can style them, otherwise we need to find another carousel component.
image


The colour scheme of the application section looks fine for now. For the Apply button, though, we can add a hover state which changes the cursor type and maybe changes the shade of the button?

**Comment by Seneli** [comment]
Hi @hellomusa I don't see those scroll bars on my end but I think its because the `overflow:scroll`  is activated. I removed this and it should be gone now. 

In terms of styling the arrows I'm ngl I chose them because I thought they wouldn't need styling so they aren't actually customizable 😅. I was thinking of switching to a different open source carousel. 

I was looking at this one: [React-multi-carousel](https://www.npmjs.com/package/react-multi-carousel), since it has customizable arrows and seems to be well maintained. Let me know your thoughts 😁

**Comment by hellomusa** [comment]
Removing `overflow: scroll` worked, nice!
The react-multi-carousel package looks to have nice support for custom arrows. Good find. Try to create an arrow like the one from the figma design

**Comment by Seneli** [comment]
Note to self: don't work on this til PR #22 is merged. There are  some breaking updates to the `App.tsx` file in this PR that are addressed there 👀

**Comment by Seneli** [comment]
Hi @AdiChops @hellomusa when you have a second mind checking this out?

https://github.com/cublueprint/cublueprint.github.io/assets/44822892/fd57ac88-fbea-4f83-891b-b8a774164663

**Review by AdiChops — CHANGES_REQUESTED** [review]
Nice job with the projects page and pages!

Some things that I noticed:

## Home Page
- On the home screen, the buttons at the top are center-aligned even though they should be left aligned (as they are in the deployed version). I think the sizing of the image at the top got a bit messed up too but that one is really small and might just be related to the alignment thing

**This branch:**
image
**Deployed version:**
image

- We might need to change the way the projects are linked on the home page projects carousel, because currently when you click on "Read More" on them, they don't lead to the specific project page, even though the link itself is the same.

**From the home page carousel**:
image

**From the projects page carousel:**
image

---
## Projects Page
- The formatting and alignment of this section at the bottom is a bit off. The button also seems to be using its own formatting rather than the button component used everywhere else
image
- The formatting gets a bit weird at a small phone screen size. This is how it looks for iPhone 4 dimensions:
image

This is how it looks on a folded Galaxy Fold:
image
For reference, the iPhone 4 width is 320px and the folded Galaxy Fold width is 280px. Phones are much wider nowadays and for the Galaxy Fold, it looks fine when it's unfolded so it shouldn't be a big deal if it isn't super great, but it would be good to support for smaller devices if possible.

---
## Project-Specific Pages
- For the project-specific pages, longer project titles seem to overflow on smaller screen sizes. For reference, this is what it looks like on the iPhone 4:
image
A more modern example, this is what it looks like on the iPhone 12 Pro:
image
Slightly better but still overflows. I think it might be better to make the font size a bit smaller. 

- The margin in front of the problem/solution looks a bit strange
image

Otherwise, everything looks good, great job!

**Comment by Seneli** [comment]
Hi @AdiChops and @hellomusa I made all the changes requested in the previous revision. Please take a look :)

**Review by AdiChops — APPROVED** [review]

**Pull request merged**
